"""Compatibility facade for external service integrations."""

from training_plan.integrations.notes import (
    _build_planner_comment_block,
    _merge_planner_comments,
    generate_weekly_report,
    save_daily_note_to_icu,
    save_morning_wellness,
    save_weekly_report_to_icu,
)
from training_plan.integrations.intervals_client import (
    fetch_activities,
    fetch_all_planned_events,
    fetch_athlete,
    fetch_fitness,
    fetch_planned_workouts,
    fetch_races,
    fetch_wellness,
    fetch_yesterday_actual,
    get_taper_config,
    icu_get,
)
from training_plan.integrations.intervals_events import (
    _parse_local_event_datetime,
    _slot_time,
    _stockholm_now_naive,
    build_hr_workout_doc,
    build_workout_step_text,
    delete_ai_workouts,
    event_has_started,
    plan_day_has_started,
    save_event,
    save_workout,
    update_manual_nutrition,
)
from training_plan.integrations.weather import YR_CODES, fetch_weather

__all__ = [
    "YR_CODES",
    "_build_planner_comment_block",
    "_merge_planner_comments",
    "_parse_local_event_datetime",
    "_slot_time",
    "_stockholm_now_naive",
    "build_hr_workout_doc",
    "build_workout_step_text",
    "delete_ai_workouts",
    "event_has_started",
    "fetch_activities",
    "fetch_all_planned_events",
    "fetch_athlete",
    "fetch_fitness",
    "fetch_planned_workouts",
    "fetch_races",
    "fetch_weather",
    "fetch_wellness",
    "fetch_yesterday_actual",
    "generate_weekly_report",
    "get_taper_config",
    "icu_get",
    "plan_day_has_started",
    "save_daily_note_to_icu",
    "save_event",
    "save_morning_wellness",
    "save_weekly_report_to_icu",
    "save_workout",
    "update_manual_nutrition",
]
